// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/codigo/Lexer.flex

package codigo;
import static codigo.Tokens.*;

@SuppressWarnings("fallthrough")
class Lexer {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\1\u0200\1\u0300\1\u0400\1\u0500\1\u0600\1\u0700"+
    "\1\u0800\1\u0900\1\u0a00\1\u0b00\1\u0c00\1\u0d00\1\u0e00\1\u0f00"+
    "\1\u1000\1\u0100\1\u1100\1\u1200\1\u1300\1\u0100\1\u1400\1\u1500"+
    "\1\u1600\1\u1700\1\u1800\1\u1900\1\u1a00\1\u1b00\1\u0100\1\u1c00"+
    "\1\u1d00\1\u1e00\12\u1f00\1\u2000\1\u2100\1\u2200\1\u1f00\1\u2300"+
    "\1\u2400\2\u1f00\31\u0100\1\u2500\121\u0100\1\u2600\4\u0100\1\u2700"+
    "\1\u0100\1\u2800\1\u2900\1\u2a00\1\u2b00\1\u2c00\1\u2d00\53\u0100"+
    "\1\u2e00\10\u2f00\31\u1f00\1\u0100\1\u3000\1\u3100\1\u0100\1\u3200"+
    "\1\u3300\1\u3400\1\u3500\1\u1f00\1\u3600\1\u3700\1\u3800\1\u3900"+
    "\1\u0100\1\u3a00\1\u3b00\1\u3c00\1\u3d00\1\u3e00\1\u3f00\1\u4000"+
    "\1\u1f00\1\u4100\1\u4200\1\u4300\1\u4400\1\u4500\1\u4600\1\u4700"+
    "\1\u4800\1\u4900\1\u4a00\1\u4b00\1\u4c00\1\u1f00\1\u4d00\1\u4e00"+
    "\1\u4f00\1\u1f00\3\u0100\1\u5000\1\u5100\1\u5200\12\u1f00\4\u0100"+
    "\1\u5300\17\u1f00\2\u0100\1\u5400\41\u1f00\2\u0100\1\u5500\1\u5600"+
    "\2\u1f00\1\u5700\1\u5800\27\u0100\1\u5900\2\u0100\1\u5a00\45\u1f00"+
    "\1\u0100\1\u5b00\1\u5c00\11\u1f00\1\u5d00\27\u1f00\1\u5e00\1\u5f00"+
    "\1\u6000\1\u6100\11\u1f00\1\u6200\1\u6300\5\u1f00\1\u6400\1\u6500"+
    "\4\u1f00\1\u6600\21\u1f00\246\u0100\1\u6700\20\u0100\1\u6800\1\u6900"+
    "\25\u0100\1\u6a00\34\u0100\1\u6b00\14\u1f00\2\u0100\1\u6c00\u0e05\u1f00";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\0\1\2\22\0\1\1\1\3"+
    "\1\4\2\0\1\5\2\0\2\6\1\7\1\10\1\6"+
    "\1\11\1\12\1\13\1\14\7\15\2\16\2\6\1\17"+
    "\1\20\1\17\2\0\6\21\21\22\1\23\2\22\1\6"+
    "\1\0\1\6\1\0\1\24\1\0\1\25\1\26\1\27"+
    "\1\30\1\31\1\32\1\33\1\34\1\35\1\22\1\36"+
    "\1\37\1\40\1\41\1\42\1\43\1\22\1\44\1\45"+
    "\1\46\1\47\1\50\1\51\1\23\1\52\1\22\1\6"+
    "\1\0\1\6\54\0\1\24\12\0\1\24\4\0\1\24"+
    "\5\0\27\24\1\0\37\24\1\0\u01ca\24\4\0\14\24"+
    "\16\0\5\24\7\0\1\24\1\0\1\24\201\0\5\24"+
    "\1\0\2\24\2\0\4\24\1\0\1\24\6\0\1\24"+
    "\1\0\3\24\1\0\1\24\1\0\24\24\1\0\123\24"+
    "\1\0\213\24\10\0\246\24\1\0\46\24\2\0\1\24"+
    "\6\0\51\24\107\0\33\24\4\0\4\24\55\0\53\24"+
    "\25\0\12\24\4\0\2\24\1\0\143\24\1\0\1\24"+
    "\17\0\2\24\7\0\17\24\2\0\1\24\20\0\1\24"+
    "\1\0\36\24\35\0\131\24\13\0\1\24\16\0\53\24"+
    "\11\0\2\24\4\0\1\24\5\0\26\24\4\0\1\24"+
    "\11\0\1\24\3\0\1\24\27\0\31\24\7\0\13\24"+
    "\65\0\25\24\1\0\10\24\106\0\66\24\3\0\1\24"+
    "\22\0\1\24\7\0\12\24\4\0\12\24\1\0\20\24"+
    "\4\0\10\24\2\0\2\24\2\0\26\24\1\0\7\24"+
    "\1\0\1\24\3\0\4\24\3\0\1\24\20\0\1\24"+
    "\15\0\2\24\1\0\3\24\4\0\14\24\12\0\1\24"+
    "\10\0\6\24\4\0\2\24\2\0\26\24\1\0\7\24"+
    "\1\0\2\24\1\0\2\24\1\0\2\24\37\0\4\24"+
    "\1\0\1\24\7\0\12\24\2\0\3\24\20\0\11\24"+
    "\1\0\3\24\1\0\26\24\1\0\7\24\1\0\2\24"+
    "\1\0\5\24\3\0\1\24\22\0\1\24\17\0\2\24"+
    "\4\0\12\24\11\0\1\24\13\0\10\24\2\0\2\24"+
    "\2\0\26\24\1\0\7\24\1\0\2\24\1\0\5\24"+
    "\3\0\1\24\36\0\2\24\1\0\3\24\4\0\12\24"+
    "\1\0\1\24\21\0\1\24\1\0\6\24\3\0\3\24"+
    "\1\0\4\24\3\0\2\24\1\0\1\24\1\0\2\24"+
    "\3\0\2\24\3\0\3\24\3\0\14\24\26\0\1\24"+
    "\25\0\12\24\25\0\10\24\1\0\3\24\1\0\27\24"+
    "\1\0\20\24\3\0\1\24\32\0\3\24\5\0\2\24"+
    "\4\0\12\24\20\0\1\24\4\0\10\24\1\0\3\24"+
    "\1\0\27\24\1\0\12\24\1\0\5\24\3\0\1\24"+
    "\40\0\1\24\1\0\2\24\4\0\12\24\1\0\2\24"+
    "\22\0\10\24\1\0\3\24\1\0\51\24\2\0\1\24"+
    "\20\0\1\24\5\0\3\24\10\0\3\24\4\0\12\24"+
    "\12\0\6\24\5\0\22\24\3\0\30\24\1\0\11\24"+
    "\1\0\1\24\2\0\7\24\37\0\12\24\21\0\60\24"+
    "\1\0\2\24\14\0\7\24\11\0\12\24\47\0\2\24"+
    "\1\0\1\24\1\0\5\24\1\0\30\24\1\0\1\24"+
    "\1\0\12\24\1\0\2\24\11\0\1\24\2\0\5\24"+
    "\1\0\1\24\11\0\12\24\2\0\4\24\40\0\1\24"+
    "\37\0\12\24\26\0\10\24\1\0\44\24\33\0\5\24"+
    "\163\0\53\24\24\0\13\24\6\0\6\24\4\0\4\24"+
    "\3\0\1\24\3\0\2\24\7\0\3\24\4\0\15\24"+
    "\14\0\1\24\1\0\12\24\6\0\46\24\1\0\1\24"+
    "\5\0\1\24\2\0\53\24\1\0\115\24\1\0\4\24"+
    "\2\0\7\24\1\0\1\24\1\0\4\24\2\0\51\24"+
    "\1\0\4\24\2\0\41\24\1\0\4\24\2\0\7\24"+
    "\1\0\1\24\1\0\4\24\2\0\17\24\1\0\71\24"+
    "\1\0\4\24\2\0\103\24\45\0\20\24\20\0\126\24"+
    "\2\0\6\24\3\0\u016c\24\2\0\21\24\1\0\32\24"+
    "\5\0\113\24\6\0\10\24\7\0\15\24\1\0\4\24"+
    "\16\0\22\24\16\0\22\24\16\0\15\24\1\0\3\24"+
    "\17\0\64\24\43\0\1\24\4\0\1\24\3\0\12\24"+
    "\46\0\12\24\6\0\131\24\7\0\5\24\2\0\42\24"+
    "\1\0\1\24\5\0\106\24\12\0\37\24\47\0\50\24"+
    "\2\0\5\24\13\0\54\24\4\0\32\24\6\0\12\24"+
    "\46\0\27\24\11\0\65\24\53\0\12\24\6\0\12\24"+
    "\15\0\1\24\135\0\57\24\21\0\7\24\4\0\12\24"+
    "\51\0\36\24\15\0\70\24\32\0\44\24\34\0\12\24"+
    "\3\0\61\24\2\0\11\24\7\0\53\24\2\0\3\24"+
    "\51\0\4\24\1\0\6\24\1\0\2\24\3\0\1\24"+
    "\5\0\300\24\100\0\26\24\2\0\6\24\2\0\46\24"+
    "\2\0\6\24\2\0\10\24\1\0\1\24\1\0\1\24"+
    "\1\0\1\24\1\0\37\24\2\0\65\24\1\0\7\24"+
    "\1\0\1\24\3\0\3\24\1\0\7\24\3\0\4\24"+
    "\2\0\6\24\4\0\15\24\5\0\3\24\1\0\7\24"+
    "\164\0\1\24\15\0\1\24\20\0\15\24\145\0\1\24"+
    "\4\0\1\24\2\0\12\24\1\0\1\24\3\0\5\24"+
    "\6\0\1\24\1\0\1\24\1\0\1\24\1\0\4\24"+
    "\1\0\13\24\2\0\4\24\5\0\5\24\4\0\1\24"+
    "\64\0\2\24\u017b\0\57\24\1\0\57\24\1\0\205\24"+
    "\6\0\4\24\3\0\2\24\14\0\46\24\1\0\1\24"+
    "\5\0\1\24\2\0\70\24\7\0\1\24\20\0\27\24"+
    "\11\0\7\24\1\0\7\24\1\0\7\24\1\0\7\24"+
    "\1\0\7\24\1\0\7\24\1\0\7\24\1\0\7\24"+
    "\120\0\1\24\325\0\2\24\52\0\5\24\5\0\2\24"+
    "\4\0\126\24\6\0\3\24\1\0\132\24\1\0\4\24"+
    "\5\0\53\24\1\0\136\24\21\0\33\24\65\0\306\24"+
    "\112\0\360\24\20\0\215\24\103\0\56\24\2\0\15\24"+
    "\3\0\34\24\24\0\57\24\20\0\37\24\2\0\106\24"+
    "\61\0\11\24\2\0\147\24\2\0\65\24\2\0\5\24"+
    "\60\0\13\24\1\0\3\24\1\0\4\24\1\0\27\24"+
    "\35\0\64\24\16\0\62\24\34\0\12\24\30\0\6\24"+
    "\3\0\1\24\1\0\2\24\1\0\46\24\12\0\27\24"+
    "\31\0\35\24\7\0\57\24\34\0\13\24\6\0\5\24"+
    "\1\0\31\24\1\0\51\24\27\0\3\24\1\0\10\24"+
    "\4\0\12\24\6\0\27\24\3\0\1\24\3\0\62\24"+
    "\1\0\1\24\3\0\2\24\2\0\5\24\2\0\1\24"+
    "\1\0\1\24\30\0\3\24\2\0\13\24\7\0\3\24"+
    "\14\0\6\24\2\0\6\24\2\0\6\24\11\0\7\24"+
    "\1\0\7\24\1\0\53\24\1\0\14\24\10\0\163\24"+
    "\15\0\12\24\6\0\244\24\14\0\27\24\4\0\61\24"+
    "\u0104\0\156\24\2\0\152\24\46\0\7\24\14\0\5\24"+
    "\5\0\1\24\1\0\12\24\1\0\15\24\1\0\5\24"+
    "\1\0\1\24\1\0\2\24\1\0\2\24\1\0\154\24"+
    "\41\0\153\24\22\0\100\24\2\0\66\24\50\0\14\24"+
    "\164\0\5\24\1\0\207\24\23\0\12\24\7\0\32\24"+
    "\6\0\32\24\13\0\131\24\3\0\6\24\2\0\6\24"+
    "\2\0\6\24\2\0\3\24\43\0\14\24\1\0\32\24"+
    "\1\0\23\24\1\0\2\24\1\0\17\24\2\0\16\24"+
    "\42\0\173\24\205\0\35\24\3\0\61\24\57\0\40\24"+
    "\15\0\24\24\1\0\10\24\6\0\46\24\12\0\36\24"+
    "\2\0\44\24\4\0\10\24\60\0\236\24\2\0\12\24"+
    "\6\0\44\24\4\0\44\24\4\0\50\24\10\0\64\24"+
    "\234\0\67\24\11\0\26\24\12\0\10\24\230\0\6\24"+
    "\2\0\1\24\1\0\54\24\1\0\2\24\3\0\1\24"+
    "\2\0\27\24\12\0\27\24\11\0\37\24\101\0\23\24"+
    "\1\0\2\24\12\0\26\24\12\0\32\24\106\0\70\24"+
    "\6\0\2\24\100\0\1\24\17\0\4\24\1\0\3\24"+
    "\1\0\35\24\52\0\35\24\3\0\35\24\43\0\10\24"+
    "\1\0\34\24\33\0\66\24\12\0\26\24\12\0\23\24"+
    "\15\0\22\24\156\0\111\24\67\0\63\24\15\0\63\24"+
    "\15\0\44\24\14\0\12\24\306\0\35\24\12\0\1\24"+
    "\10\0\26\24\232\0\27\24\14\0\65\24\56\0\12\24"+
    "\23\0\55\24\40\0\31\24\7\0\12\24\11\0\44\24"+
    "\17\0\12\24\4\0\1\24\13\0\43\24\3\0\1\24"+
    "\14\0\60\24\16\0\4\24\13\0\13\24\1\0\1\24"+
    "\43\0\22\24\1\0\31\24\124\0\7\24\1\0\1\24"+
    "\1\0\4\24\1\0\17\24\1\0\12\24\7\0\57\24"+
    "\21\0\12\24\13\0\10\24\2\0\2\24\2\0\26\24"+
    "\1\0\7\24\1\0\2\24\1\0\5\24\3\0\1\24"+
    "\22\0\1\24\14\0\5\24\236\0\65\24\22\0\4\24"+
    "\5\0\12\24\5\0\1\24\40\0\60\24\24\0\2\24"+
    "\1\0\1\24\10\0\12\24\246\0\57\24\51\0\4\24"+
    "\44\0\60\24\24\0\1\24\13\0\12\24\46\0\53\24"+
    "\15\0\1\24\7\0\12\24\66\0\33\24\25\0\12\24"+
    "\306\0\54\24\164\0\112\24\25\0\1\24\240\0\10\24"+
    "\2\0\47\24\20\0\1\24\1\0\1\24\34\0\1\24"+
    "\12\0\50\24\7\0\1\24\25\0\1\24\13\0\56\24"+
    "\23\0\1\24\42\0\71\24\7\0\11\24\1\0\45\24"+
    "\21\0\1\24\17\0\12\24\30\0\36\24\160\0\7\24"+
    "\1\0\2\24\1\0\46\24\25\0\1\24\11\0\12\24"+
    "\6\0\6\24\1\0\2\24\1\0\40\24\16\0\1\24"+
    "\7\0\12\24\u0136\0\23\24\15\0\232\24\346\0\304\24"+
    "\274\0\57\24\321\0\107\24\271\0\71\24\7\0\37\24"+
    "\1\0\12\24\146\0\36\24\22\0\60\24\20\0\4\24"+
    "\14\0\12\24\11\0\25\24\5\0\23\24\260\0\100\24"+
    "\200\0\113\24\5\0\1\24\102\0\15\24\100\0\2\24"+
    "\1\0\1\24\34\0\370\24\10\0\363\24\15\0\37\24"+
    "\61\0\3\24\21\0\4\24\10\0\u018c\24\4\0\153\24"+
    "\5\0\15\24\3\0\11\24\7\0\12\24\146\0\125\24"+
    "\1\0\107\24\1\0\2\24\2\0\1\24\2\0\2\24"+
    "\2\0\4\24\1\0\14\24\1\0\1\24\1\0\7\24"+
    "\1\0\101\24\1\0\4\24\2\0\10\24\1\0\7\24"+
    "\1\0\34\24\1\0\4\24\1\0\5\24\1\0\1\24"+
    "\3\0\7\24\1\0\u0154\24\2\0\31\24\1\0\31\24"+
    "\1\0\37\24\1\0\31\24\1\0\37\24\1\0\31\24"+
    "\1\0\37\24\1\0\31\24\1\0\37\24\1\0\31\24"+
    "\1\0\10\24\2\0\137\24\12\0\7\24\2\0\12\24"+
    "\4\0\1\24\u0171\0\54\24\4\0\12\24\6\0\305\24"+
    "\73\0\104\24\7\0\1\24\4\0\12\24\246\0\4\24"+
    "\1\0\33\24\1\0\2\24\1\0\1\24\2\0\1\24"+
    "\1\0\12\24\1\0\4\24\1\0\1\24\1\0\1\24"+
    "\6\0\1\24\4\0\1\24\1\0\1\24\1\0\1\24"+
    "\1\0\3\24\1\0\2\24\1\0\1\24\2\0\1\24"+
    "\1\0\1\24\1\0\1\24\1\0\1\24\1\0\1\24"+
    "\1\0\2\24\1\0\1\24\2\0\4\24\1\0\7\24"+
    "\1\0\4\24\1\0\4\24\1\0\1\24\1\0\12\24"+
    "\1\0\21\24\5\0\3\24\1\0\5\24\1\0\21\24"+
    "\104\0\327\24\51\0\65\24\13\0\336\24\2\0\u0182\24"+
    "\16\0\u0131\24\37\0\36\24\342\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[27904];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\1\1\3\1\4\1\5\3\4"+
    "\2\6\1\4\1\7\1\10\20\7\1\11\1\12\1\13"+
    "\1\0\1\14\1\15\1\16\5\7\1\17\13\7\1\12"+
    "\1\20\1\21\15\7\1\22\15\7";

  private static int [] zzUnpackAction() {
    int [] result = new int[85];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\53\0\126\0\201\0\254\0\327\0\327\0\u0102"+
    "\0\u012d\0\u0158\0\u0183\0\u01ae\0\201\0\u01d9\0\u0204\0\u022f"+
    "\0\u025a\0\u0285\0\u02b0\0\u02db\0\u0306\0\u0331\0\u035c\0\u0387"+
    "\0\u03b2\0\u03dd\0\u0408\0\u0433\0\u045e\0\u0489\0\u04b4\0\327"+
    "\0\u04df\0\u050a\0\u0535\0\u0560\0\u058b\0\u05b6\0\u05e1\0\u060c"+
    "\0\u0637\0\u0662\0\u068d\0\u01d9\0\u06b8\0\u06e3\0\u070e\0\u0739"+
    "\0\u0764\0\u078f\0\u07ba\0\u07e5\0\u0810\0\u083b\0\u0866\0\u0891"+
    "\0\u0535\0\u05b6\0\u08bc\0\u08e7\0\u0912\0\u093d\0\u0968\0\u0993"+
    "\0\u09be\0\u09e9\0\u0a14\0\u0a3f\0\u0a6a\0\u0a95\0\u0ac0\0\327"+
    "\0\u0aeb\0\u0b16\0\u0b41\0\u0b6c\0\u0b97\0\u0bc2\0\u0bed\0\u0c18"+
    "\0\u0c43\0\u0c6e\0\u0c99\0\u0cc4\0\u0cef";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[85];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\4\1\5\1\6\1\7\1\6\1\10"+
    "\1\11\1\7\1\12\1\13\2\14\2\15\3\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\2\16\1\26"+
    "\2\16\1\27\1\30\1\31\1\32\1\33\1\34\1\35"+
    "\1\16\1\36\1\37\1\16\1\2\53\0\2\3\70\0"+
    "\1\6\32\0\2\5\1\0\1\5\1\40\46\5\63\0"+
    "\1\6\53\0\1\6\50\0\1\41\3\0\1\42\51\0"+
    "\1\43\1\0\2\44\1\45\2\0\2\17\1\46\27\17"+
    "\12\0\1\43\1\0\3\14\2\0\32\17\14\0\3\16"+
    "\2\0\3\16\1\17\26\16\14\0\3\17\2\0\32\17"+
    "\14\0\3\16\2\0\3\16\1\17\14\16\1\47\2\16"+
    "\1\50\6\16\14\0\3\16\2\0\3\16\1\17\15\16"+
    "\1\51\1\16\1\52\6\16\14\0\3\16\2\0\3\16"+
    "\1\17\15\16\1\53\10\16\14\0\3\16\2\0\3\16"+
    "\1\17\15\16\1\54\10\16\14\0\3\16\2\0\3\16"+
    "\1\17\12\16\1\55\13\16\14\0\3\16\2\0\3\16"+
    "\1\17\1\24\11\16\1\56\2\16\1\31\4\16\1\57"+
    "\3\16\14\0\3\16\2\0\3\16\1\17\5\16\1\54"+
    "\6\16\1\60\11\16\14\0\3\16\2\0\3\16\1\17"+
    "\1\61\25\16\14\0\3\16\2\0\3\16\1\17\15\16"+
    "\1\60\10\16\14\0\3\16\2\0\3\16\1\17\17\16"+
    "\1\54\6\16\14\0\3\16\2\0\3\16\1\17\17\16"+
    "\1\62\6\16\14\0\3\16\2\0\3\16\1\17\4\16"+
    "\1\63\21\16\14\0\3\16\2\0\3\16\1\17\21\16"+
    "\1\64\4\16\14\0\3\16\2\0\3\16\1\17\17\16"+
    "\1\65\6\16\14\0\3\16\2\0\3\16\1\17\1\31"+
    "\14\16\1\66\10\16\14\0\3\16\2\0\3\16\1\17"+
    "\7\16\1\67\16\16\7\41\1\70\43\41\2\42\1\0"+
    "\50\42\14\0\3\71\46\0\1\43\1\0\2\44\1\45"+
    "\2\0\32\17\12\0\1\43\1\0\3\45\2\0\32\17"+
    "\14\0\3\72\2\0\1\72\3\17\6\72\20\17\14\0"+
    "\3\16\2\0\3\16\1\17\3\16\1\54\22\16\14\0"+
    "\3\16\2\0\3\16\1\17\17\16\1\73\6\16\14\0"+
    "\3\16\2\0\3\16\1\17\15\16\1\74\10\16\14\0"+
    "\3\16\2\0\3\16\1\17\4\16\1\75\21\16\14\0"+
    "\3\16\2\0\3\16\1\17\14\16\1\76\11\16\14\0"+
    "\3\16\2\0\3\16\1\17\20\16\1\77\5\16\14\0"+
    "\3\16\2\0\3\16\1\17\15\16\1\100\10\16\14\0"+
    "\3\16\2\0\3\16\1\17\14\16\1\101\11\16\14\0"+
    "\3\16\2\0\3\16\1\17\21\16\1\54\4\16\14\0"+
    "\3\16\2\0\3\16\1\17\10\16\1\102\15\16\14\0"+
    "\3\16\2\0\3\16\1\17\10\16\1\103\4\16\1\104"+
    "\10\16\14\0\3\16\2\0\3\16\1\17\1\47\20\16"+
    "\1\105\4\16\14\0\3\16\2\0\3\16\1\17\17\16"+
    "\1\106\6\16\14\0\3\16\2\0\3\16\1\17\22\16"+
    "\1\77\3\16\14\0\3\16\2\0\3\16\1\17\10\16"+
    "\1\47\15\16\14\0\3\16\2\0\3\16\1\17\10\16"+
    "\1\107\15\16\7\41\1\70\3\41\1\110\37\41\14\0"+
    "\3\16\2\0\3\16\1\17\1\111\25\16\14\0\3\16"+
    "\2\0\3\16\1\17\12\16\1\54\13\16\14\0\3\16"+
    "\2\0\3\16\1\17\1\112\25\16\14\0\3\16\2\0"+
    "\3\16\1\17\20\16\1\60\1\113\4\16\14\0\3\16"+
    "\2\0\3\16\1\17\4\16\1\54\21\16\14\0\3\16"+
    "\2\0\3\16\1\17\1\60\25\16\14\0\3\16\2\0"+
    "\3\16\1\17\2\16\1\114\23\16\14\0\3\16\2\0"+
    "\3\16\1\17\14\16\1\54\11\16\14\0\3\16\2\0"+
    "\3\16\1\17\14\16\1\60\11\16\14\0\3\16\2\0"+
    "\3\16\1\17\6\16\1\115\17\16\14\0\3\16\2\0"+
    "\3\16\1\17\22\16\1\116\3\16\14\0\3\16\2\0"+
    "\3\16\1\17\10\16\1\117\15\16\14\0\3\16\2\0"+
    "\3\16\1\17\12\16\1\77\13\16\14\0\3\16\2\0"+
    "\3\16\1\17\25\16\1\54\14\0\3\16\2\0\3\16"+
    "\1\17\11\16\1\54\14\16\14\0\3\16\2\0\3\16"+
    "\1\17\10\16\1\120\15\16\14\0\3\16\2\0\3\16"+
    "\1\17\21\16\1\121\4\16\14\0\3\16\2\0\3\16"+
    "\1\17\17\16\1\122\6\16\14\0\3\16\2\0\3\16"+
    "\1\17\17\16\1\102\6\16\14\0\3\16\2\0\3\16"+
    "\1\17\14\16\1\123\11\16\14\0\3\16\2\0\3\16"+
    "\1\17\14\16\1\65\11\16\14\0\3\16\2\0\3\16"+
    "\1\17\10\16\1\124\15\16\14\0\3\16\2\0\3\16"+
    "\1\17\1\125\25\16\14\0\3\16\2\0\3\16\1\17"+
    "\6\16\1\54\17\16\14\0\3\16\2\0\3\16\1\17"+
    "\15\16\1\102\10\16\14\0\3\16\2\0\3\16\1\17"+
    "\13\16\1\54\12\16";

  private static int [] zzUnpacktrans() {
    int [] result = new int[3354];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\4\1\2\11\30\1\1\11\2\1\1\0\44\1"+
    "\1\11\15\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[85];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
    public String lexeme;
    public int line;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Tokens yylex() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { lexeme=yytext(); line=yyline+1; return ERRORES;
            }
          // fall through
          case 19: break;
          case 2:
            { /* ignorar espacios */
            }
          // fall through
          case 20: break;
          case 3:
            { lexeme=yytext(); line=yyline+1; return ERROR_STRING_SIN_CERRAR;
            }
          // fall through
          case 21: break;
          case 4:
            { lexeme=yytext(); line=yyline+1; return OPERADORES;
            }
          // fall through
          case 22: break;
          case 5:
            { lexeme=yytext(); line=yyline+1; return SEPARADORES;
            }
          // fall through
          case 23: break;
          case 6:
            { lexeme=yytext(); line=yyline+1; return LITERALES_NUMEROS;
            }
          // fall through
          case 24: break;
          case 7:
            { lexeme=yytext(); line=yyline+1; return IDENTIFICADORES;
            }
          // fall through
          case 25: break;
          case 8:
            { lexeme=yytext(); line=yyline+1; return ERROR_IDENTIFICADOR;
            }
          // fall through
          case 26: break;
          case 9:
            { lexeme=yytext(); line=yyline+1; return LITERALES_STRINGS;
            }
          // fall through
          case 27: break;
          case 10:
            { lexeme=yytext(); line=yyline+1; return ERROR_COMENTARIO_SIN_CERRAR;
            }
          // fall through
          case 28: break;
          case 11:
            { /*Ignorar linea*/
            }
          // fall through
          case 29: break;
          case 12:
            { lexeme=yytext(); line=yyline+1; return LITERALES_OCTALES;
            }
          // fall through
          case 30: break;
          case 13:
            { lexeme=yytext(); line=yyline+1; return ERROR_OCTAL;
            }
          // fall through
          case 31: break;
          case 14:
            { lexeme=yytext(); line=yyline+1; return ERROR_HEXADECIMAL;
            }
          // fall through
          case 32: break;
          case 15:
            { lexeme=yytext(); line=yyline+1; return PALABRAS_RESERVADAS;
            }
          // fall through
          case 33: break;
          case 16:
            { lexeme=yytext(); line=yyline+1; return LITERALES_FLOTANTES;
            }
          // fall through
          case 34: break;
          case 17:
            { lexeme=yytext(); line=yyline+1; return LITERALES_HEXADECIMALES;
            }
          // fall through
          case 35: break;
          case 18:
            { /*Ignorar bloque*/
            }
          // fall through
          case 36: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
